Add default window size in windowing int test
confluentinc/ksql pull request #10483
Opened 2024-10-21 07:29 UTC by VedarthConfluent

### Description 
This fixes the ksql build by updating the usage of `TimeWindowedDeserializer`

### Testing done 
Ran build and tests locally

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")
- [ ] Do these changes have compatibility implications for rollback? If so, ensure that the ksql [command version](https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java#L41) is bumped.

2024-10-21 08:47 UTC, trnguyencflt approved these changes

2024-10-21 08:48 UTC, trnguyencflt commented
It looks like we got related failed tests

2024-10-21 09:12 UTC, hrishabhg requested changes
Need context on PR.

2024-10-21 09:17 UTC, VedarthConfluent commented on ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
> +      new TimeWindowedDeserializer<>(STRING_DESERIALIZER, DEFAULT_WINDOW_SIZE);
Updated PR desription

2024-10-21 14:30 UTC, VedarthConfluent commented
The changes introduced in this PR seem to be stable. There are few test failures but they are not related to this change

2024-10-21 15:04 UTC, trnguyencflt commented
> The changes introduced in this PR seem to be stable. There are few test failures but they are not related to this change

@VedarthConfluent ksql still needs to tests to pass to publish jars, shall we disable the tests to unblock the build process and file a jira ticket to fix those tests later?

2024-10-21 18:20 UTC, mjsax commented on ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
> +      new TimeWindowedDeserializer<>(STRING_DESERIALIZER, DEFAULT_WINDOW_SIZE);
There is no "default" window size -- this must be the actual window size of the data we want to deserialize.

Thus, I think we should pass in `Duration.ofSeconds(10).toMillis()` here, and also update the `shouldAggregateTumblingWindow()` and `shouldAggregateHoppingWindow()` accordingly.

Just found this PR after I hit this issue locally...

2024-10-22 05:03 UTC, VedarthConfluent commented on ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
> +      new TimeWindowedDeserializer<>(STRING_DESERIALIZER, DEFAULT_WINDOW_SIZE);
Build succeeds with warnings when deprecated API is used, hence this was never detected.
Made the recommended changes

2024-10-22 15:11 UTC, mjsax approved these changes

2024-10-22 15:13 UTC, mjsax commented on ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
> +      new TimeWindowedDeserializer<>(STRING_DESERIALIZER, DEFAULT_WINDOW_SIZE);
Thanks.

I think you should consider to enable failing the build, or it's a manual process to watch out for deprecation warnings and file ticket to move of deprecated APIs (there is always at least a deprecation time frame of 1 year before things are removed, so maybe manually observing w/o failing the build could be sufficient).

2024-10-23 04:00 UTC, hrishabhg approved these changes

2024-10-23 04:00 UTC, merged