[KSE-1612] Upgrade netty to 4.1.87
confluentinc/ksql pull request #9764
Opened 2023-01-19 15:29 UTC by rkhachatryan

This fixes CVE-2022-41881 and, potentially, CVE-2022-41915 vulnerabilities.

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

2023-01-19 16:46 UTC, zentol requested changes
Should also upgrade tcnative to 2.0.56.
Note that this version incorporates https://github.com/netty/netty/pull/13112 so there may or may not be potential to streamline some infrastructure.

2023-01-19 19:02 UTC, rkhachatryan commented
Thanks @zentol !
I've upgraded netty-tcnative as well.

2023-01-19 20:04 UTC, zentol approved these changes
Approving because github forces me to; cant mark the previous review as resolved without approving :/

2023-01-20 11:29 UTC, rkhachatryan commented
I've updraded vert.x as well because it uses netty too.
The latest available vert.x version is `4.3.7` which depends on netty `4.1.86` and tcnative `2.54` - so I picked these versions.

I've also checked `io.confluent:common` which ksql depends on.  It depends on netty as well - [currently](https://github.com/confluentinc/common/blob/4e9c1d8a5e05b947228e7772b0530894e9d3ec54/pom.xml#L88) (as of `7.4.0`), on version `4.1.79`. That is already out of sync with ksql (`4.1.68`).

2023-01-20 12:49 UTC, lucasbru commented
Hey @rkhachatryan 

we previously had the problem that ksql standalone images wouldn't start up because ksql is compiled with a different netty version than the version that ksql-images gets from `io.confluent:common`. To avoid that this will happen again, I think it should be sufficient to update the netty version here as well: https://github.com/confluentinc/ksql-images/blob/master/pom.xml#L130 So that ksql-images is packaged with the correct netty version.

See https://confluentinc.atlassian.net/browse/KSE-1529

Thanks, Lucas

2023-01-20 13:48 UTC, lucasbru requested changes
(ignore this)

2023-01-20 13:50 UTC, lucasbru approved these changes
Ah, I didn't follow the whole discussion. I support if we update it 4.1.86 no upgrade of tcnative is necessary. Then, +2 from me

2023-01-20 13:55 UTC, rkhachatryan commented
Thanks @lucasbru!
I've opened https://github.com/confluentinc/ksql-images/pull/100 to update `ksql-images`.
I'm going to merge this PR and then `ksql-images` after the version bump by CI.

(yes, tcnative doesn't have to be updated)

2023-01-20 14:01 UTC, merged